# Generated by Django 5.2.7 on 2025-10-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='kit',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kit',
            name='destination_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kit',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='needs_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kit',
            name='status',
            field=models.CharField(choices=[('in-use', 'In Use'), ('in-transit', 'In Transit'), ('maintenance', 'Maintenance')], default='in_use', max_length=20),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('event_date', models.DateField()),
                ('raw_text', models.TextField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kit')),
            ],
        ),
    ]
