# Generated by Django 5.2.7 on 2025-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_kit_serial_number_kit_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmortem',
            name='raw_text',
        ),
        migrations.AddField(
            model_name='postmortem',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmortem',
            name='restock',
            field=models.TextField(blank=True, null=True),
        ),
    ]
