# Generated by Django 5.2.7 on 2025-10-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_postmortem_raw_text_postmortem_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmortem',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
