# Generated by Django 5.2.7 on 2025-10-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postmortem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
