# Generated by Django 5.2.7 on 2025-11-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kit_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='status',
        ),
    ]
